# Generated by Django 5.0.2 on 2024-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householder_app', '0002_rename_am_creditor_95_person99_amcrdtr_95_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person99',
            name='GenderId',
            field=models.IntegerField(),
        ),
    ]
