# Generated by Django 5.0.2 on 2024-02-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('householder_app', '0003_alter_person99_genderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person99',
            name='BimeSalmat_Type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person99',
            name='Senf',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person99',
            name='isurban',
            field=models.CharField(max_length=10),
        ),
    ]
