# Generated by Django 5.0.2 on 2024-02-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('householder_app', '0004_rename_last_prd_95_person99_lstprd_95_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person99',
            old_name='last_prd_95',
            new_name='lstPrd_95',
        ),
    ]
